version: "3.8"

services:
  mongodb:
    image: "mongo"
    container_name: studynotion-mongodb
    ports:
      - "27016:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: studynotion-backend
    env_file:
      - ./server/.env
    ports:
      - "${BACKEND_PORT:-4000}:4000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://studynotion-mongodb:27017/studynotion

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: "http://localhost:${BACKEND_PORT:-4000}/api/v1"
    restart: unless-stopped
    container_name: studynotion-frontend
    ports:
      - "${FRONTEND_PORT:-5173}:80"

volumes:
  mongodb_data:



# docker compose up -d --build
